version: '3.2'
services:
  spring-boot:
    build: .
    ports:
      - '${SPRING_BOOT_PORT}:9090'
    depends_on:
      - mariadb
    networks:
      - book_net
  mariadb:
    image: 'mariadb:10.5'
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_HOST=%'
      - 'TZ="Asia/Seoul"'
      - 'MYSQL_DATABASE=book'
    volumes:
      - './mysql/conf.d:/etc/mysql/conf.d'
      - '~/docker/${PROJECT_NAME}/var/lib/mysql:/var/lib/mysql'
    networks:
      - book_net
networks:
  book_net:
    driver: bridge



